name: Deploy Vuepress
on:
    push:
      branches:
        - main
env:
    TZ: Asia/Shanghai

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout 🛎️
            uses: actions/checkout@v2.3.1
            with:
                persist-credentials: false

          - name: Install and Build 🔧
            run: |
                npm install
                npm run build

          - name: Deploy 🚀
            uses: peaceiris/actions-gh-pages@v3.7.3
            with:
                github_token: ${{ secrets.ACCESS_TOKEN }}
                publish_dir: docs/.vuepress/dist
                commit_message: ${{ github.event.head_commit.message }}
                keep_files: true
                